/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.abbts.sya;

import javax.xml.ws.Endpoint;

public class App {

    public static void main(String[] args) {

        System.out.println("Starting Endpoint");
        Endpoint.publish("http://10.0.1.10:8080/orakel/getSpell", new Orakel());
        System.out.println("Done!\nWaiting for connection...");

    }
}
